# Generated by Django 4.2.11 on 2024-05-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='grade',
            new_name='classes',
        ),
    ]
